repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.2
    hooks:
    -   id: isort
        exclude: migrations

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: check-merge-conflict
      exclude: migrations,hosting

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      args: [--ignore, E501]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        exclude: migrations