# Generated by Django 3.2.11 on 2022-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=1000)),
                ("src", models.CharField(max_length=10)),
                ("dest", models.CharField(max_length=10)),
            ],
        ),
    ]
