# Generated by Django 3.2.11 on 2022-01-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_languagedefault"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LanguageDefault",
            new_name="DefaultTranslation",
        ),
    ]
