# Generated by Django 3.2.11 on 2022-01-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_languagedefault_defaulttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttranslation',
            name='dest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defaulttranslation',
            name='src_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
