version: '3.8'

services:
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=thinhntg
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bot_database
    ports:
      - "5433:5432"

  app:
    restart: always
    build:
      context: ../
    command: /app/app_production_entrypoint.sh
    volumes:
      - static_volume:/app/static/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ../telebot/.env_production

  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - static_volume:/app/static/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - app

  bots:
    restart: always
    build:
      context: ../
    command:
      - python
      - manage.py
      - run_bots
    depends_on:
      - db
    env_file:
      - ../telebot/.env_production

volumes:
  postgres_data:
  static_volume:
